### ISSUE TITLE
Build breaks due to nin-ascii chars in README

### ISSUE THREAD

**Issue by yurivict** [bjodah/symcxx#19]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 136, in <module>
    long_description = open('README.rst').read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3019: ordinal not in range(128)
```

This is because you have non-ascii characters in README.

**Comment by bjodah** [comment]
Thanks, should (hopefully) work since gh-20.
